export const companySizes: string[] = [
  '1',
  '2-10',
  '11-50',
  '51-200',
  '201-500',
  '501-1000',
  '1001-5000',
  '5001-10,000',
  '10,000+'
];

export const industries: string[] = [
  "Aerospace and Defense",
  "Agriculture and Forestry",
  "Automotive",
  "Banks",
  "Chemicals",
  "Civic, Non-Profit and Membership Groups",
  "Computer Hardware",
  "Computer Software",
  "Construction and Building Materials",
  "Consumer Products",
  "Consumer Services",
  "Corporate Services",
  "Electronics",
  "Energy and Environmental",
  "Financial Services",
  "Food and Beverage",
  "Government",
  "Holding Companies ",
  "Hospitals and Healthcare",
  "Industrial Manufacturing and Services",
  "Insurance",
  "Leisure, Sports and Recreation",
  "Media",
  "Mining and Metals",
  "Pharmaceuticals and Biotech",
  "Real Estate Services",
  "Retail",
  "Schools and Education",
  "Telecommunications",
  "Transportation"
];
